config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'

  resources :orders
  get '/profit_details' => 'orders#profit_details'

  resources :customers, only: [:index]

  resources :products, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::SessionStorage


  def with_shopify!
    session = ShopifyAPI::Session.new(shopify_domain, shopify_token)
    ShopifyAPI::Base.activate_session(session)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ShopifyApp::AuthenticatedController

  def index
    @customers = ShopifyAPI::Customer.find(:all, params: { limit: 10 })
  end

 end

app/controllers/home_controller.rb
class HomeController < ShopifyApp::AuthenticatedController
  skip_before_action :verify_authenticity_token, only: :update_order_details, raise: false

  def index
  end

end

app/controllers/orders_controller.rb
class OrdersController < ShopifyApp::AuthenticatedController

  def index
    @orders = ShopifyAPI::Order.find(:all, params: { limit: 10 })
  end

  def edit
    @order = ShopifyAPI::Order.find(params['id'])
  end

  def update
    order = ShopifyAPI::Order.find(params[:shopify_api_order][:order_id])
    order.shipping_address = params[:shopify_api_order].to_unsafe_h
    order.save
    if params[:shopify_api_order][:tracking_number].present?
      order.fulfillments.first.update_attributes(order_id: order.id, tracking_numbers: [params[:shopify_api_order][:tracking_number]])
    end
    redirect_to action: 'index'
  end

  def profit_details
    data_points = [["00:00", 0]]
    start_time = Time.now.midnight
    for i in 1..23
      end_time = start_time + i.hour
      total_revenue = ShopifyAPI::Order.where(created_at_min: start_time, created_at_max: end_time).map{|a| a.total_price.to_f }.sum.round
      supplier_cost = (total_revenue * 0.2).round
      marketing_cost = (total_revenue * 0.4).round
      profit = (i-1 < Time.now.strftime("%H").to_i ) ? (total_revenue - supplier_cost - marketing_cost) : ''
      data_points << [end_time.strftime("%H:00"), profit]
    end
    render json: data_points
  end

 end

app/controllers/products_controller.rb
class ProductsController < ShopifyApp::AuthenticatedController

  def index
    @products = ShopifyAPI::Product.find(:all, params: { limit: 10 })
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/index.html.erb
<h2>Customers</h2>

 <ul>
  <% @customers.each do |customer| %>
    <li><%= link_to customer.email, "https://#{@shop_session.url}/admin/customers/#{customer.id}", target: "_blank" %></li>
  <% end %>
</ul>

 <hr>
<%= link_to "Back", root_path %> 

app/views/home/get_order.html.erb
<h2> Order Details: </h2>

<%= form_for :order, url: "/details" do |f| %>
  Order: <%= f.text_field :order_id, value: @order.try(:id) %> <br><br>
  <h3> Tracking Code: </h3>
  <% if @order.try(:fulfillments).present? %>
    <% fulfillment = @order.try(:fulfillments).first %>
    Tracking Code<%= f.text_field :tracking_number, value: fulfillment.tracking_number %> <br><br>
  <% else %>
    <h5> No fulfillment available for this order </h5>
  <% end %>
  <h3> Shipping Address: </h3>
  <% if @order.try(:shipping_address).present? %>
    <% order = @order.try(:shipping_address).attributes %>
    First Name<%= f.text_field :first_name, value: order[:first_name] %> <br><br>
    Last Name<%= f.text_field :last_name, value: order[:last_name] %> <br><br>
    Phone<%= f.text_field :phone, value: order[:phone] %> <br><br>
    Address 1<%= f.text_area :address1, value: order[:address1] %> <br><br>
    Address 2<%= f.text_area :address2, value: order[:address2] %> <br><br>
    City<%= f.text_field :city, value: order[:city] %> <br><br>
    Province<%= f.text_field :province, value: order[:province] %> <br><br>
    Country<%= f.text_field :country, value: order[:country] %> <br><br>
    Zip<%= f.text_field :zip, value: order[:zip] %> <br><br>
  <% else %>
    <h5> No shipping address available for this order </h5>
  <% end %>
  <%= f.submit%>
<% end  %>

app/views/home/index.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({ title: "Home" });
    });
  </script>
<% end %>
<%= javascript_include_tag 'application' %>

<h2>List of Orders</h2>

<%= link_to 'Click here', orders_path%>

<hr>

<h2>List of Customers</h2>

<%= link_to 'Click here', customers_path%>

<hr>

<h2>Profit Chart for <%= Date.today.to_s(:long) %></h2>
<p> (Time Zone is in UTC) </p>

<%= line_chart profit_details_path %>

<hr>

<h2>List of Products</h2>

<%= link_to 'Click here', products_path%>

<hr>

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
<script type="text/javascript">
  var eventName = typeof(Turbolinks) !== 'undefined' ? 'turbolinks:load' : 'DOMContentLoaded';

  if (!document.documentElement.hasAttribute("data-turbolinks-preview")) {
    document.addEventListener(eventName, function flash() {
      <% if flash[:notice] %>
        ShopifyApp.flashNotice(<%== flash[:notice].to_json %>);
      <% end %>

      <% if flash[:error] %>
        ShopifyApp.flashError(<%== flash[:error].to_json %>);
      <% end %>
                             
      document.removeEventListener(eventName, flash)
    });
  }
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopifyDev</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>

    <script type="text/javascript">
      ShopifyApp.init({
        apiKey: "<%= ShopifyApp.configuration.api_key %>",
        shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
        debug: <%= Rails.env.development? ? 'true' : 'false' %>,
        forceRedirect: true
      });
    </script>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>

app/views/orders/edit.html.erb
<h2> Order Details: </h2>

<%= form_for @order, url: order_path(@order) do |f| %>
  Order: <%= f.text_field :order_id, value: @order.try(:id) %> <br><br>
  <h3> Tracking Code: </h3>
  <% if @order.try(:fulfillments).present? %>
    <% fulfillment = @order.try(:fulfillments).first %>
    Tracking Code<%= f.text_field :tracking_number, value: fulfillment.tracking_number %> <br><br>
  <% else %>
    <h5> No fulfillment available for this order </h5>
  <% end %>
  <h3> Shipping Address: </h3>
  <% if @order.try(:shipping_address).present? %>
    <% order = @order.try(:shipping_address).attributes %>
    First Name<%= f.text_field :first_name, value: order[:first_name] %> <br><br>
    Last Name<%= f.text_field :last_name, value: order[:last_name] %> <br><br>
    Phone<%= f.text_field :phone, value: order[:phone] %> <br><br>
    Address 1<%= f.text_area :address1, value: order[:address1] %> <br><br>
    Address 2<%= f.text_area :address2, value: order[:address2] %> <br><br>
    City<%= f.text_field :city, value: order[:city] %> <br><br>
    Province<%= f.text_field :province, value: order[:province] %> <br><br>
    Country<%= f.text_field :country, value: order[:country] %> <br><br>
    Zip<%= f.text_field :zip, value: order[:zip] %> <br><br>
  <% else %>
    <h5> No shipping address available for this order </h5>
  <% end %>
  <%= f.submit%>
<% end  %>

app/views/orders/index.html.erb
<h2>Orders</h2>

 <ul>
  <% @orders.each do |order| %>
    <li><%= link_to order.name, "https://#{@shop_session.url}/admin/orders/#{order.id}", target: "_blank" %>  <%= link_to "Edit", edit_order_path(order.id) %></li>
<% end %>
</ul>
<hr>
<%= link_to "Back", root_path %>

app/views/products/index.html.erb
<h2>Products</h2>

 <ul>
  <% @products.each do |product| %>
    <li><%= link_to product.title, "https://#{@shop_session.url}/admin/products/#{product.id}", target: "_blank" %></li>
  <% end %>
</ul>

 <hr>
<%= link_to "Back", root_path %>